"use strict";var fmkControllers=angular.module("fmkControllers",[]);fmkControllers.constant("AUTH_EVENTS",{loginSuccess:"auth-login-success",loginFailure:"auth-login-failure",logoutSuccess:"auth-logout-success",sessionTimeout:"auth-session-timeout",notAuthenticated:"auth-not-authenticated",notAuthorized:"auth-not-authorized"});
fmkControllers.constant("KWP_LIST_DATA",{firstName:{attr:"firstName",header:"First Name"},lastName:{attr:"lastName",header:"Last Name"},email:{attr:"email",header:"E-Mail"}});fmkControllers.controller("LoginController",["$scope","$routeParams","$http","AUTH_EVENTS","UserService",function(a,b,e,c,d){a.credentials={username:b.username,password:""};
a.processing=false;a.login=function(f){a.$broadcast("autofill:update");a.processing=true;a.loginForm.error=null;d.login(f).success(function(g){if(g.sessionId){window.localStorage.setItem("sessionId",g.sessionId);
e.defaults.headers.common.SessionId=g.sessionId}a.$emit(c.loginSuccess,g)}).error(function(h,g){a.processing=false;a.$emit(c.loginFailure,h);a.loginForm.error=h})};a.logout=function(){d.logout(window.localStorage.getItem("sessionId")).success(function(){window.localStorage.removeItem("sessionId");
e.defaults.headers.common.SessionId="";a.$emit(c.logoutSuccess)}).error(function(){window.localStorage.removeItem("sessionId");e.defaults.headers.common.SessionId="";a.$emit(c.logoutSuccess);window.location="#"
})};a.forgottenPassword=function(){a.$broadcast("autofill:update");a.processing=true;d.newUserPassword(a.credentials.username).success(function(){a.processing=false;window.location="#/login"}).error(function(){a.processing=false;
window.location="#"})}}]);fmkControllers.controller("RegisterController",["$scope","CommonServices","UserService",function(a,b,c){a.registrationInfo={username:"",email:"",firstName:"",lastName:"",password:"",password2:"",address:null};
a.processing=false;a.register=function(d){a.processing=true;c.register(d).success(function(e){window.location="#/activation"}).error(function(f,e){b.handleHttpErrorResponse(a,f,e)})}}]);fmkControllers.controller("ActivationController",["$scope","$routeParams","CommonServices","UserService",function(a,b,c,d){a.processing=false;
a.activate=function(e){a.processing=true;console.log("ActivationController::activate("+e+")");d.activate(e).success(function(f){window.location="#/login?username="+f.username}).error(function(g,f){a.processing=false;
c.handleHttpErrorResponse(a,g,f);a.activationForm.error=g})};console.log("ActivationController|key="+b.key);if(b.key){a.activate(b.key)}}]);fmkControllers.controller("AuthErrorController",["$scope",function(a){}]);
fmkControllers.controller("AdminController",["$scope","$interval","CommonServices","UserService","SessionService",function(i,e,c,d,b){i.users=[];console.log("$scope.roles="+i.roles);var k=[];k.push({attr:"username",header:"Username",direc:"user-link"});
k.push({attr:"firstName",header:"First name",direc:"kwp-field-data"});k.push({attr:"lastName",header:"Last name",direc:"kwp-field-data"});k.push({attr:"lSLTMs",header:"Last login",direc:"kwp-field-data"});
i.usersListData=k;i.processing=true;var f=function(){d.getAll().success(function(l){i.users=l.allusers;i.$broadcast("usersRefreshList",l.allusers);i.processing=false}).error(function(m,l){c.handleHttpErrorResponse(i,m,l)
})};f();i.$on("usersRemoveItem",function(m,l,n){d.deleteUser(l).success(function(o){f()}).error(function(p,o){c.handleHttpErrorResponse(i,p,o)})});i.sessions=[];var a=[];a.push({attr:"user.username",header:"Username",direc:"session-user-link"});
a.push({attr:"lastTimestamp",header:"Last timestamp",direc:"kwp-field-data"});i.sessionsListData=a;var g=function(){b.getAll().success(function(l){i.sessions=l.allsessions;i.$broadcast("sessionsRefreshList",l.allsessions)
}).error(function(m,l){c.handleHttpErrorResponse(i,m,l)})};g();i.$on("sessionsRemoveItem",function(m,l,n){b.destroy(l).success(function(o){g()}).error(function(p,o){c.handleHttpErrorResponse(i,p,o)})});
var j=e(function(){f()},60*1000);var h=e(function(){g()},10*1000);i.$on("$destroy",function(){e.cancel(j);e.cancel(h)})}]);fmkControllers.controller("UserProfileController",["$scope","CommonServices",function(a,b){}]);
fmkControllers.controller("UserAddressController",["$scope","CommonServices","UserService",function(a,b,c){if(!a.user){a.user=a.currentUser}if(a.user.address!==null){a.address={line1:a.user.address.line1,line2:a.user.address.line2,postalCode:a.user.address.postalCode,town:a.user.address.town,province:a.user.address.province,state:a.user.address.state}
}else{a.address={line1:"",line2:"",postalCode:"",town:"",province:"",state:""}}a.setAddress=function(d){a.processing=true;c.setUserAddress(a.user.username,d).success(function(e){a.user=e.user;a.processing=false
}).error(function(f,e){b.handleHttpErrorResponse(a,f,e);a.processing=false})}}]);fmkControllers.controller("ChangePasswordController",["$scope","CommonServices","UserService",function(a,b,c){a.credentials={currentPassword:"",password:"",password2:"",};
if(a.tmpPassword){a.credentials.currentPassword=a.tmpPassword}a.changePassword=function(d){a.processing=true;c.changeUserPassword(a.user.username,d.currentPassword,d.password).success(function(e){a.processing=false
}).error(function(f,e){b.handleHttpErrorResponse(a,f,e);a.processing=false})}}]);fmkControllers.controller("ListController",["$scope","$filter","$interpolate","Pagination",function(a,d,c,b){a.itemClick=function(e){a.onItemClick({item:e})
};if(a.listSize){b.init(a,a.orderBy,a.listSize)}else{b.init(a,a.orderBy,50)}a.updateFilter=function(){var e=d("filter")(a.list,function(g){if(!a.searchString){return true}var f=c("{{"+a.searchBy+"}}")(g);
return f.toLowerCase().indexOf(a.searchString.toLowerCase())!==-1});b.updatePage(a,e)};a.prevPage=function(){b.prevPage(a)};a.nextPage=function(){b.nextPage(a)};a.sortBy=function(e){b.sortBy(a,e)};a.setPage=function(){b.setPage(a,this.n)
};a.range=function(h,e){var f=[];if(!e){e=h;h=0}for(var g=h;g<e;g++){f.push(g)}return f};a.removeItemCallback=function(e){b.updatePage(a,e)};a.remove=function(e){a.$emit(a.listId+"RemoveItem",e,a.removeItemCallback)
};a.$on(a.listId+"RefreshList",function(e,f){b.updatePage(a,f)});b.updatePage(a,a.list)}]);fmkControllers.controller("MessagesController",["$scope","$filter","Pagination",function(a,c,b){if(a.listSize){b.init(a,a.orderBy,a.listSize)
}else{b.init(a,a.orderBy,50)}a.messageFilter="ALL";a.updateFilter=function(e){if(a.messageFilter==e){a.messageFilter="ALL"}else{a.messageFilter=e}var d=c("filter")(a.list,function(f){if(a.messageFilter=="ALL"){return true
}return f.level==e});b.updatePage(a,d)};a.prevPage=function(){b.prevPage(a)};a.nextPage=function(){b.nextPage(a)};a.sortBy=function(d){b.sortBy(a,d)};a.setPage=function(){b.setPage(a,this.n)};a.range=function(g,d){var e=[];
if(!d){d=g;g=0}for(var f=g;f<d;f++){e.push(f)}return e};a.$on(a.listId+"RefreshList",function(d,e){b.updatePage(a,e)});b.updatePage(a,a.list);if(a.list.length>0){a.opened="in"}}]);fmkControllers.directive("wrapper",["$compile",function(a){var b={};
b.restrict="E";b.compile=function(d,c){var e=function(g,h,f){h.replaceWith(a("<"+g.data.direc+" item='item' data='data' field='data.attr'/>")(g))};return e};b.scope={item:"=",data:"="};return b}]);fmkControllers.directive("userLink",[function(){var a={};
a.restrict="EC";a.template="<a class='linkElement' href='#/user?username={{user.username}}'>{{user.username}}</a>";a.scope={user:"=item",};return a}]);fmkControllers.directive("sessionUserLink",[function(){var a={};
a.restrict="EC";a.template="<a class='linkElement' href='#/user?id={{session.user.username}}'>{{session.user.username}}</a>";a.scope={session:"=item",};return a}]);fmkControllers.directive("userrolesEdit",[function(){var a={};
a.restrict="EC";a.template="test";a.scope={user:"=item",data:"="};a.controller=function(b,c){console.log("userrolesEditController");b.selectedRole=null;b.showtooltip=false;b.hideTooltip=function(){b.showtooltip=false
};b.toggleTooltip=function(d){d.stopPropagation();console.log("InlineEditorController"+JSON.stringify(b.user));b.showtooltip=!b.showtooltip};b.addRole=function(){c.addUserRole(b.user.username,b.selectedRole).success(function(d){b.user=d.user;
b.showtooltip=false}).error(function(e,d){CommonServices.handleHttpErrorResponse(b,e,d)})};b.removeRole=function(){c.removeUserRole(b.user.username,b.selectedRole).success(function(d){b.user=d.user;b.showtooltip=false
}).error(function(e,d){CommonServices.handleHttpErrorResponse(b,e,d)})}};return a}]);fmkControllers.directive("userroleEdit",[function(){var a={};a.restrict="EC";a.template="<td><img src='img/edit.png' ng-hide='showtooltip'ng-click='toggleTooltip($event)' height='21'/><span ng-hide='showtooltip'>{{user.role}}</span><span ng-show='showtooltip'><img ng-click='newRole=user.role;toggleTooltip($event)' src='img/close.png' height='21' /><select ng-model='newRole' ng-options='o.name as o.name for o in data.roles'></select><img src='img/save.png' height='21' ng-click='changeRole()' /></span></td> ";
a.scope={user:"=item",data:"="};a.controller=function(b,c){b.newRole=b.user.role;b.showtooltip=false;b.hideTooltip=function(){b.showtooltip=false};b.toggleTooltip=function(d){d.stopPropagation();console.log("InlineEditorController"+JSON.stringify(b.user));
b.showtooltip=!b.showtooltip};b.changeRole=function(){c.addUserRole(b.user.username,b.newRole).success(function(d){b.user=d.user;b.showtooltip=false}).error(function(e,d){CommonServices.handleHttpErrorResponse(b,e,d)
})}};return a}]);fmkControllers.controller("ContactMessageController",["$scope","$timeout","CommonServices","ContactMessageService",function(b,c,e,a){b.processing=false;b.message={senderName:"",subject:"",body:""};
var d=null;b.sendMessage=function(f){b.processing=true;a.sendMessage(f).success(function(h){b.processing=false;b.messageSent=true;d=c(function g(){window.location="#"},2000)}).error(function(h,g){e.handleHttpErrorResponse(b,h,g);
b.processing=false})};b.$on("$destroy",function(f){if(d!=null){c.cancel(d)}})}]);fmkControllers.controller("UploadCtrl",["$scope","fileUpload",function(a,b){a.add=function(){var d=document.getElementById("fileToUpload").files[0],e=new FileReader();
if(d){var c=0;if(d.size>1024*1024){c=(Math.round(d.size*100/(1024*1024))/100).toString()+"MB"}else{c=(Math.round(d.size*100/1024)/100).toString()+"KB"}a.fileName=d.name;a.fileSize=c;a.fileType=d.type}e.readAsArrayBuffer(d);
b.uploadFileToUrl(d,"updwnld")}}]);"use strict";var fmkDirectives=angular.module("fmkDirectives",["fmkServices"]);fmkDirectives.directive("kwpAutoComplete",["$timeout",function(a){return{controller:["$scope","$element","$attrs",function(d,c,b){console.log("kwpAutoComplete:"+b.kwpAutoCompleteItems);
console.log("kwpAutoComplete:"+d[b.kwpAutoCompleteItems]);var e=["test1","test2","test3","test4","ietsanders"];c.autocomplete({source:e})}]}}]);fmkDirectives.directive("kwpPwCheck",[function(){return{require:"ngModel",link:function(c,e,a,d){var b=e.inheritedData("$formController")[a.kwpPwCheck];
d.$parsers.push(function(f){if(f===b.$viewValue){d.$setValidity("pwdMatch",true);return f}d.$setValidity("pwdMatch",false)});b.$parsers.push(function(f){d.$setValidity("pwdMatch",f===d.$viewValue);return f
})}}}]);fmkDirectives.directive("kwpUserExists",["CommonServices","UserService",function(a,b){return{require:"ngModel",link:function(d,e,c,f){e.on("blur",function(g){console.log("kwpUserExists::blur "+g);
d.$apply(function(){var i=e.val();var h={username:i,};b.exists(h).success(function(j){console.log("kwpUserExists::exists "+j.exists);f.$setValidity("user",!j.exists)}).error(function(k,j){a.handleHttpErrorResponse($scope,k,j)
})})})}}}]);fmkDirectives.directive("kwpCustomDirective",["$compile",function(a){return{restrict:"E",scope:false,link:function(f,c,b){console.log("kwpCustomDirective::link type="+b.type+",attributes="+b.attributes);
var e="<div "+b.type;if(b.attributes){e+=" "+b.attributes}e+=" ></div>";var d=a(e)(f);c.append(d)}}}]);fmkDirectives.directive("kwpAutoFill",[function(){return{require:"ngModel",link:function(c,b,a,d){c.$on("autofill:update",function(){d.$setViewValue(b.val())
})}}}]);fmkDirectives.directive("kwpConfirmClick",[function(){return{restrict:"A",link:function(c,b,a){b.bind("click",function(){var e=c.$eval(a.kwpConfirmCondition);if(e){var d=a.kwpConfirmMessage;if(d&&confirm(d)){c.$apply(a.kwpConfirmClick)
}}else{c.$apply(a.kwpConfirmClick)}})}}}]);fmkDirectives.directive("kwpUpload",["CommonServices",function(a){var b={};b.restrict="E";b.replace=true;b.template="<div class='row'><span class='col-md-4 btn btn-success fileinput-button'><i class='glyphicon glyphicon-upload'></i>&nbsp; <span>{{uploadBtnName}}</span> <input type='file' id='fileToUpload' name='fileToUpload' ng-disabled='percentCompleted>0'><img ng-show='percentCompleted>0' class='inprogress' src='fmk_img/processing.gif' /></input></span><div ng-if='percentCompleted>0' class='progress col-md-8'><div class='progress-bar' role='progressbar' aria-valuenow='{{percentCompleted}}' aria-valuemin='0' aria-valuemax='100' style='width: {{percentCompleted}}%;'>{{percentCompleted}}%</div></div></div>";
b.scope={uploadBtnName:"@",uploadUrl:"@",onUploaded:"&"};b.link=function(f,d,c){f.percentCompleted=-1;if(!f.uploadBtnName){f.uploadBtnName="Upload file..."}var e=function(){var m=d.find("#fileToUpload")[0];
f.files=[];for(var j=0;j<m.files.length;j++){f.files.push(m.files[j])}var h=f.files[0],k=new FileReader();k.readAsArrayBuffer(h);var g=new FormData();g.append("file",h);var l=new XMLHttpRequest();f.$apply(function(){f.percentCompleted=0
});l.upload.onprogress=function(i){if(i.lengthComputable){f.$apply(function(){f.percentCompleted=Math.round(i.loaded/i.total*100)})}};l.upload.onload=function(i){f.$apply(function(){f.percentCompleted=-1
})};l.open("POST",HTTP_ROOT+f.uploadUrl);l.setRequestHeader("SessionId",window.localStorage.getItem("sessionId"));l.onreadystatechange=function(i){if(l.readyState==4){if(l.status==200){if(f.onUploaded){f.onUploaded(JSON.parse(l.responseText))
}}else{console.log("kwpUpload::onreadystatechange error");a.handleHttpErrorResponse(f,"onreadystatechange",l.status)}}};l.send(g)};d.bind("change",e)};return b}]);fmkDirectives.directive("kwpBackButton",function(){return{restrict:"A",link:function(d,c,b){c.bind("click",a);
function a(){history.back();d.$apply()}}}});fmkDirectives.directive("kwpDraggable",function(){return{scope:{kwpDraggableItem:"@",kwpParentId:"@",kwpToggleDragging:"&",},link:function(c,a){var b=a[0];b.draggable=true;
b.addEventListener("dragstart",function(f){f.dataTransfer.effectAllowed="move";var d={object:c.kwpDraggableItem,parentId:c.kwpParentId};f.dataTransfer.setData("Text",JSON.stringify(d));this.classList.add("drag");
if(c.kwpToggleDragging){c.kwpToggleDragging({dragging:true})}return false},false);b.addEventListener("dragend",function(d){this.classList.remove("drag");if(c.kwpToggleDragging){c.kwpToggleDragging({dragging:false})
}return false},false)}}});fmkDirectives.directive("kwpDroppable",function(){return{scope:{kwpOnDrop:"&"},link:function(c,a){var b=a[0];b.addEventListener("dragover",function(d){d.dataTransfer.dropEffect="move";
if(d.preventDefault){d.preventDefault()}this.classList.add("over");return false},false);b.addEventListener("dragenter",function(d){this.classList.add("over");return false},false);b.addEventListener("dragleave",function(d){this.classList.remove("over");
return false},false);b.addEventListener("drop",function(f){if(f.preventDefault){f.preventDefault()}if(f.stopPropagation){f.stopPropagation()}this.classList.remove("over");var d=JSON.parse(f.dataTransfer.getData("Text"));
if(b.id===d.parentId){console.log("kwpDroppable::drop Cannot drop on parent");return false}if(c.kwpOnDrop){c.kwpOnDrop({object:JSON.parse(d.object)})}return false},false)}}});fmkDirectives.directive("kwpAnimateOnChange",["$animate",function(a){return{controller:["$scope","$element","$attrs",function(d,c,b){d.$watch(b.kwpAnimateOnChange,function(e,f){if(e!=f){var g=b.kwpAnimateOnChangeClass;
a.addClass(c,g,function(){a.removeClass(c,g)})}})}]}}]);fmkDirectives.directive("kwpFieldData",["$interpolate",function(a){var b={};b.restrict="E";b.compile=function(d,c){var e=function(g,h,f){var i=a("{{item."+g.data.attr+"}}")(g);
h.html(i)};return e};b.scope={item:"=",data:"=",};return b}]);"use strict";var fmkFilters=angular.module("fmkFilters",[]);fmkFilters.filter("kwpUpperCaseFirstThenLower",["$filter",function(a){return function(b){return(!!b)?b.charAt(0).toUpperCase()+b.substr(1).toLowerCase():""
}}]);fmkFilters.filter("kwpUpperCase",["$filter",function(a){return function(b){return(!!b)?b.toUpperCase():""}}]);fmkFilters.filter("kwpCharAt",["$filter",function(a){return function(b,c){return(!!b)?b.charAt(c):""
}}]);fmkFilters.filter("kwpNoSpace",["$filter",function(){return function(a){return(!a)?"":a.replace(/ /g,"")}}]);fmkFilters.filter("kwpRemoveSpecialChars",["$filter",function(a){return function(c){var b="!@#$^&%*()+=-[]/{}|:<>?,.";
for(var d=0;d<b.length;d++){c=c.replace(new RegExp("\\"+b[d],"gi"),"")}return c}}]);fmkFilters.filter("kwpSplit",["$filter",function(a){return function(b,d,c){return b.split(d)[c]}}]);fmkFilters.filter("percentage",["$filter",function(a){return function(c,b){var e=parseFloat(a("number")(c*100,b));
var d=e.toString();return d+"%"}}]);"use strict";var fmkServices=angular.module("fmkServices",["ngResource"]);fmkServices.factory("CommonServices",["$http","AUTH_EVENTS",function(b,a){return{handleHttpErrorResponse:function(e,d,c){switch(c){case 400:console.log("fmkServices/CommonServices::handleHttpErrorResponse HTTP status "+c+", Bad Request");
window.location="#/internal_error";break;case 403:e.$emit(a.notAuthorized);break;case 408:console.log("fmkServices/CommonServices::handleHttpErrorResponse HTTP status "+c+", REQUEST_TIMEOUT: "+d.errorReason);
location.reload();break;case 412:console.log("fmkServices/CommonServices::handleHttpErrorResponse HTTP status "+c+", Server Precondition failed : "+d.errorReason);break;case 419:console.log("fmkServices/CommonServices::handleHttpErrorResponse HTTP status "+c+", Authentication/Session timeout : "+d.errorReason);
window.localStorage.removeItem("sessionId");b.defaults.headers.common.SessionId="";e.$emit(a.sessionTimeout);break;case 500:console.log("fmkServices/CommonServices::handleHttpErrorResponse HTTP status "+c+", Internal Server Error, reason :"+d.errorReason);
window.location="#/internal_error";break;default:console.log("fmkServices/CommonServices::handleHttpErrorResponse HTTP status "+c+", Default, reason :"+d.errorReason);window.location="#/internal_error";
break}}}}]);fmkServices.factory("ConfigurationServices",["$http","AUTH_EVENTS",function(b,a){return{getConfiguration:function(){return b.get(HTTP_ROOT+"configuration")},getUniqueId:function(){return b.get(HTTP_ROOT+"configuration/uniqueid")
}}}]);fmkServices.factory("SessionService",["$http",function(a){return{getAll:function(){return a.get("sessions")},destroy:function(b){return a({method:"DELETE",url:HTTP_ROOT+"sessions/"+b.id})}}}]);fmkServices.factory("ContactMessageService",["$http",function(a){return{sendMessage:function(b){return a.post(HTTP_ROOT+"contactmessage",b)
}}}]);fmkServices.factory("Pagination",["$filter",function(c){var b=function(e){e.pagedItems=[];if(!e.allItems){return}for(var d=0;d<e.allItems.length;d++){if(d%e.itemsPerPage===0){e.pagedItems[Math.floor(d/e.itemsPerPage)]=[e.allItems[d]]
}else{e.pagedItems[Math.floor(d/e.itemsPerPage)].push(e.allItems[d])}}};var a=function(d){d.allItems=c("orderBy")(d.allItems,d.sortingOrder,d.reverse)};return{init:function(f,d,e){f.sortingOrder=d;f.reverse=false;
f.allItems=[];f.groupedItems=[];f.itemsPerPage=e;f.pagedItems=[];f.currentPage=0},updatePage:function(e,d){e.allItems=d;if(e.sortingOrder!==""){a(e)}e.currentPage=0;b(e)},sortBy:function(e,d){e.reverse=!e.reverse;
e.sortingOrder=d;a(e);b(e)},prevPage:function(d){if(d.currentPage>0){d.currentPage--}},nextPage:function(d){if(d.currentPage<d.pagedItems.length-1){d.currentPage++}},setPage:function(e,d){e.currentPage=d
}}}]);fmkServices.factory("FileUpload",["$http",function(a){return{uploadFileToUrl:function(d,b){var c=new FormData();c.append("file",d);return a.post(HTTP_ROOT+b,c,{transformRequest:angular.identity,headers:{"Content-Type":undefined}})
}}}]);fmkControllers.controller("UserController",["$scope","$filter","$routeParams","$location","CommonServices","UserService",function(a,d,b,g,c,f){var e=b.username;a.username=e;a.processing=true;f.getUserByUsername(e).success(function(h){a.user=h;
a.processing=false}).error(function(i,h){c.handleHttpErrorResponse(a,i,h);a.processing=false});a.addRole=function(){console.log("addRole("+a.selectedRole.name+")");f.addUserRole(e,a.selectedRole.name).success(function(h){a.user=h.user;
a.processing=false}).error(function(i,h){c.handleHttpErrorResponse(a,i,h);a.processing=false})};a.removeRole=function(){console.log("removeRole("+a.selectedRole.name+")");f.removeUserRole(e,a.selectedRole.name).success(function(h){a.user=h.user;
a.processing=false}).error(function(i,h){c.handleHttpErrorResponse(a,i,h);a.processing=false})}}]);fmkDirectives.directive("kwpServerPagedList",[function(){var a={};a.restrict="E";a.templateUrl="./fmk_include/serverpagination.html";
a.scope={parentId:"@",listTitle:"@",listTitleAdmin:"=",listFactory:"@",listFactoryParams:"=",listName:"@",listId:"@",listUri:"@",listData:"=",pageSize:"@",listLayout:"@",allowLayoutToggle:"=",itemsGridDirective:"@",itemsTableDirective:"@",listSearchDirective:"@",listSearchParams:"=",listAddEnabled:"=",listAddDirective:"@",listAddParams:"=",orderBy:"@",orderReverse:"=",searchCriteriasBase:"=",searchCriterias:"=",opened:"@",onItemClick:"&",allowRemove:"=",allowDrop:"=",onListModified:"&",listParam:"@"};
a.controller=["$scope","$element","$attrs","$http","PagedListsService","CommonServices",function(k,l,j,i,m,c){console.log("kwpServerPagedList[listAddEnabled="+k.listAddEnabled+",listAddDirective="+k.listAddDirective+"]");
k.displayAction="";var d={};if(typeof(k.searchCriterias)!=="undefined"){d=k.searchCriterias}var f=Number(j.pageSize);k.orderReverseHash={};if((typeof(k.orderBy)!=="undefined")&&(typeof(j.orderReverse)!=="undefined")){k.orderReverseHash[k.orderBy]=j.orderReverse
}else{k.orderReverseHash[k.orderBy]=false}k.itemDragging=false;k.setItemDragging=function(n){k.$apply(function(){k.itemDragging=n})};var h=function(n){if(n.sessionId){i.defaults.headers.common.SessionId=n.sessionId
}k.paged=n.paged;k.items=n.items;if(k.itemsFullSize!=n.itemsFullSize){k.onListModified()}k.itemsFullSize=n.itemsFullSize;k.itemsFilteredSize=n.itemsFilteredSize;k.currentPage=Math.ceil(n.fromIndex/f);k.nbPages=Math.ceil(k.itemsFilteredSize/f)
};var b=function(o){console.log("kwpServerPagedList.doUpdateList("+k.listId+")");var n=k.currentPage*f;m.updateList(k.listUri,k.listId,o,n,f).success(function(p){h(p)}).error(function(q,p){c.handleHttpErrorResponse(k,q,p)
})};k.addItem=function(o,n){console.log("kwpServerPagedList::addItem("+o+","+JSON.stringify(n)+")");delete k.errorReason;m.addItem(k.listUri,k.listId,o,n).success(function(p){h(p);if(p.done===true){k.displayAction=""
}else{k.errorReason=p.errorReason}}).error(function(q,p){c.handleHttpErrorResponse(k,q,p)})};k.onAdd=function(n){console.log("kwpServerPagedList.onAdd("+k.listId+")");if(n.listId){b(n)}else{var o=k.currentPage*f;
m.addItem(k.listUri,k.listId,n.id,n).success(function(p){h(p)}).error(function(q,p){c.handleHttpErrorResponse(k,q,p)})}};if(k.allowRemove){k.onRemove=function(n){console.log("kwpServerPagedList::onRemove("+JSON.stringify(n)+")");
if(n.listId){console.log("onRemove(listId="+n.listId+")");n.remove=true;b(n)}else{m.removeItem(k.listUri,k.listId,n.id).success(function(o){h(o)}).error(function(p,o){c.handleHttpErrorResponse(k,p,o)})
}}}var g=function(n){m.getPage(k.listUri,k.listId,n,f).success(function(o){h(o)}).error(function(p,o){c.handleHttpErrorResponse(k,p,o)})};this.getPage=g;k.prevPage=function(){if(k.currentPage>0){g((k.currentPage-1)*f)
}};k.nextPage=function(){if(k.currentPage<(k.nbPages-1)){g((k.currentPage+1)*f)}};k.sortBy=function(n){k.orderBy=n;if(typeof(k.orderReverseHash[k.orderBy])!=="undefined"){k.orderReverseHash[k.orderBy]=!k.orderReverseHash[k.orderBy]
}else{k.orderReverseHash[k.orderBy]=false}var o=Math.ceil(k.currentPage*f);m.orderList(k.listUri,k.listId,k.orderBy,k.orderReverseHash[k.orderBy],o,f).success(function(p){h(p)}).error(function(q,p){c.handleHttpErrorResponse(k,q,p)
})};k.search=function(n){console.log("kwpServerPagedList::search("+JSON.stringify(n)+"), listId="+k.listId);m.searchList(k.listUri,k.listId,k.listName,n,k.orderBy,k.orderReverseHash[k.orderBy],0,f).success(function(o){h(o)
}).error(function(p,o){c.handleHttpErrorResponse(k,p,o)})};k.currentPage=0;var e=function(){console.log("kwpServerPagedList.doCreateList("+k.listFactory+"'"+k.listId+","+JSON.stringify(k.searchCriteriasBase)+")");
m.createList(k.listUri,k.listFactory,k.listFactoryParams,k.listId,k.listName,k.searchCriteriasBase,d,k.orderBy,k.orderReverseHash[k.orderBy],0,f).success(function(n){h(n);console.log("Broadcasting:"+k.listId+"Created");
k.$broadcast(k.listId+"Created")}).error(function(o,n){c.handleHttpErrorResponse(k,o,n)})};e();k.$on(k.listId+"RefreshList",function(n){console.log("kwpServerPagedList:"+k.listId+"RefreshList");g(0)});
k.$on(k.listId+"CreateList",function(n){console.log("kwpServerPagedList:"+k.listId+"CreateList");e()})}];a.link=function(d,c,b){d.itemClick=function(e){if(d.onItemClick){d.onItemClick({item:e})}}};return a
}]);fmkDirectives.directive("usersGrid",function(){return{replace:true,restrict:"ECA",templateUrl:"./fmk_include/users_grid.html"}});fmkDirectives.directive("usersTable",function(){return{replace:true,restrict:"ECA",templateUrl:"./fmk_include/users_table.html"}
});fmkServices.factory("MongoDBService",["$http",function(a){return{getDocument:function(b,c,d){return a.get(HTTP_ROOT+encodeURI(b+"/"+c+"/"+d))},getDistincts:function(c,e,d,b){return a.put(HTTP_ROOT+encodeURI(c+"/"+e),{distinct:d,query:b})
},getDocuments:function(c,d,b){return a.put(HTTP_ROOT+encodeURI(c+"/"+d),{query:b})},addDocument:function(c,d,e,b){return a.post(HTTP_ROOT+encodeURI(c+"/"+d+"/"+e),b)},updateDocument:function(c,d,e,b){return a.put(HTTP_ROOT+encodeURI(c+"/"+d+"/"+e),b)
}}}]);fmkServices.factory("PagedListsService",["$http",function(a){return{createList:function(c,f,g,h,b,m,d,e,i,l,j){console.log("PagedListService::createList("+f+")");var k={factory:f,factoryParams:g,listName:b,searchCriteriasBase:m,searchCriterias:d,sortCriteria:e,reverse:i,fromIndex:l,pageSize:j};
return a.post(HTTP_ROOT+encodeURI(c+"/"+h),k)},addItem:function(e,b,f,d){var c={item:d};console.log("PagedListsService.addItem called "+d);return a.post(HTTP_ROOT+encodeURI(e+"/"+b+"/"+f),c)},updateList:function(f,c,g,d,b){var e={from:g,fromIndex:d,pageSize:b};
console.log("PagedListsService.updateList called");return a.put(HTTP_ROOT+encodeURI(f+"/"+c),e)},removeItem:function(c,b,d){return a["delete"](HTTP_ROOT+encodeURI(c+"/"+b+"/"+d))},searchList:function(c,f,b,d,e,g,j,h){var i={listName:b,searchCriterias:d,sortCriteria:e,reverse:g,fromIndex:j,pageSize:h};
return a.put(HTTP_ROOT+encodeURI(c+"/"+f),i)},orderList:function(g,c,h,d,e,b){var f={sortCriteria:h,reverse:d,fromIndex:e,pageSize:b};return a.put(HTTP_ROOT+encodeURI(g+"/"+c),f)},getPage:function(e,c,d,b){return a.get(HTTP_ROOT+encodeURI(e+"/"+c+"/"+d+"/"+b))
}}}]);fmkServices.factory("UserService",["$http",function(a){return{login:function(b){return a.post(encodeURI(HTTP_ROOT+"auth"),b)},logout:function(b){return a({method:"DELETE",url:encodeURI(HTTP_ROOT+"auth/"+b)})
},register:function(b){return a.post(HTTP_ROOT+"users?action=register",b)},activate:function(b){return a.get(encodeURI(HTTP_ROOT+"activation/"+b))},exists:function(b){return a.post(HTTP_ROOT+"users?action=exists",b)
},getAll:function(){return a.get(HTTP_ROOT+"users?action=getAllUsers")},getUser:function(c){var b={sessionId:c};return a.post(HTTP_ROOT+"users?action=getUser",b)},getUserByUsername:function(c){var b={username:c};
return a.post(HTTP_ROOT+"users?action=getUser",b)},addUserRole:function(d,c){var b={username:d,role:c};return a.post(HTTP_ROOT+"users?action=addUserRole",b)},removeUserRole:function(d,c){var b={username:d,role:c};
return a.post(HTTP_ROOT+"users?action=removeUserRole",b)},setUserAddress:function(d,b){var c={username:d,address:b};return a.post(HTTP_ROOT+"users?action=setUserAddress",c)},changeUserPassword:function(e,d,c){var b={username:e,currentPassword:d,newPassword:c};
return a.post(HTTP_ROOT+"users?action=changeUserPasswconsoleord",b)},newUserPassword:function(c){var b={username:c,};return a.post(HTTP_ROOT+"users?action=newUserPassword",b)},deleteUser:function(b){return a.post(HTTP_ROOT+"users?action=deleteUser",b)
}}}]);